main: me.rootdeibis.orewards.ORewardsMain
name: orewards
version: 2.0-pre
api-version: "1.13"
author: "Deibis A - Alias rootDeibis"
website: "https://discord.gg/rxvsppR2ss"
description: "This is a recoded version of the original orewards, With this plugin you can create rewards for your player by time"
softdepend:
  - PlaceholderAPI